/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.AsistenciaDAO;
import dao.EmpleadoDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Asistencia;

/**
 *
 * @author chemo
 */
public class VtnLoginAsistencia extends javax.swing.JDialog
{

    private boolean acceso = false;

    /**
     * Creates new form VtnLoginAdministrador
     */
    public VtnLoginAsistencia(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setIconImage(getIconImage());
        
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contraseñaTF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        correoJT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mostrarCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicia Sesion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        contraseñaTF.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(contraseñaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("CONTRASEÑA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        correoJT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(correoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 340, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("CORREO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        mostrarCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        mostrarCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mostrarCheckBox.setText("Mostrar Contraseña");
        mostrarCheckBox.setToolTipText("");
        mostrarCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mostrarCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String correo = correoJT.getText().trim();
        String contra = contraseñaTF.getText().trim();

        if (correo.isEmpty() || contra.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor ingresa correo y contraseña.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        AsistenciaDAO asistenciaDAO = new AsistenciaDAO();

        int idEmpleado = empleadoDAO.validarCredenciales(correo, contra);

        if (idEmpleado != -1)
        {

            LocalDateTime ahora = LocalDateTime.now();
            Date fechaActual = Date.from(ahora.atZone(ZoneId.systemDefault()).toInstant());

            Asistencia nuevaAsistencia = new Asistencia(0, idEmpleado, fechaActual);
            boolean registrada = asistenciaDAO.insertarAsistencia(nuevaAsistencia);

            if (registrada)
            {
                SimpleDateFormat formato = new SimpleDateFormat("HH:mm dd/MM/yyyy");
                String fechaFormateada = formato.format(fechaActual);

                JOptionPane.showMessageDialog(this, "Asistencia registrada a las: " + fechaFormateada, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else
            {
                JOptionPane.showMessageDialog(this, "Error al registrar asistencia.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else
        {
            JOptionPane.showMessageDialog(this, "Credenciales inválidas", "Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(correoJT, contraseñaTF);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostrarCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mostrarCheckBoxActionPerformed
    {//GEN-HEADEREND:event_mostrarCheckBoxActionPerformed
        if (mostrarCheckBox.isSelected())
        {
            contraseñaTF.setEchoChar((char) 0);
        } else
        {
            contraseñaTF.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarCheckBoxActionPerformed

    public boolean isAcceso()
    {
        return acceso;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnLoginAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnLoginAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnLoginAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnLoginAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnLoginAsistencia dialog = new VtnLoginAsistencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaTF;
    private javax.swing.JTextField correoJT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mostrarCheckBox;
    // End of variables declaration//GEN-END:variables
}
