/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Vehiculo;

/**
 *
 * @author chemo
 */
public class VtnPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VtnPrincipal
     */
    public VtnPrincipal()
    {
        initComponents();
        setIconImage(getIconImage());
        empleado.setEnabled(false);
        asistencia.setEnabled(false);

    }
    
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelControl = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        administrador = new javax.swing.JMenu();
        login = new javax.swing.JMenu();
        empleado = new javax.swing.JMenu();
        asistencia = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taller Mecanico Autofix");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelControl.setBackground(new java.awt.Color(255, 255, 255));
        panelControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelControl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 520));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hombre.png"))); // NOI18N
        jMenu1.setText("Dueños");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carros.png"))); // NOI18N
        jMenu2.setText("Vehiculos");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja-de-herramientas.png"))); // NOI18N
        jMenu3.setText("Mantenimientos");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marca.png"))); // NOI18N
        jMenu4.setText("Asistencia");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alquiler.png"))); // NOI18N
        administrador.setText("Administrador");
        administrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        administrador.setFocusable(false);
        administrador.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        administrador.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                administradorMouseClicked(evt);
            }
        });

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos-del-usuario.png"))); // NOI18N
        login.setText("Iniciar Sesion");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        login.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                loginMouseClicked(evt);
            }
        });
        administrador.add(login);

        empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado-de-oficina.png"))); // NOI18N
        empleado.setText("Empleados");
        empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empleado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        empleado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                empleadoMouseClicked(evt);
            }
        });
        empleado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                empleadoActionPerformed(evt);
            }
        });
        administrador.add(empleado);

        asistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista-de-verificacion.png"))); // NOI18N
        asistencia.setText("Asistencia");
        asistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asistencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        asistencia.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                asistenciaMouseClicked(evt);
            }
        });
        administrador.add(asistencia);

        jMenuBar1.add(administrador);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu1MouseClicked
    {//GEN-HEADEREND:event_jMenu1MouseClicked
        panelControl.removeAll();
        VtnDueño dueño = new VtnDueño();
        panelControl.add(dueño).setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu2MouseClicked
    {//GEN-HEADEREND:event_jMenu2MouseClicked
        panelControl.removeAll();
        VtnVehiculos vehiculo = new VtnVehiculos();
        panelControl.add(vehiculo).setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu3MouseClicked
    {//GEN-HEADEREND:event_jMenu3MouseClicked
        panelControl.removeAll();
        VtnMantenimientos mantenimientos = new VtnMantenimientos();
        panelControl.add(mantenimientos).setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void administradorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_administradorMouseClicked
    {//GEN-HEADEREND:event_administradorMouseClicked

    }//GEN-LAST:event_administradorMouseClicked

    private void empleadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_empleadoMouseClicked
    {//GEN-HEADEREND:event_empleadoMouseClicked
        boolean activo = empleado.isEnabled();
        
        if (activo)
        {
            panelControl.removeAll();
            CtrlInterfaz.habilita(true, empleado, asistencia);
            VtnEmpleados empleados = new VtnEmpleados();
            panelControl.add(empleados).setVisible(true);
        }else
        {
            JOptionPane.showMessageDialog(this, "Inicie sesion como administrador", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_empleadoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, empleado, asistencia);
    }//GEN-LAST:event_formWindowOpened

    private void loginMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_loginMouseClicked
    {//GEN-HEADEREND:event_loginMouseClicked
        VtnLoginAdministrador login = new VtnLoginAdministrador(this, true);
        login.setVisible(true);

        if (login.isAcceso())
        {
            panelControl.removeAll();
            empleado.setEnabled(true);
            asistencia.setEnabled(true);

        } else
        {
            System.out.println("Acceso denegado");
        }
    }//GEN-LAST:event_loginMouseClicked

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_empleadoActionPerformed
    {//GEN-HEADEREND:event_empleadoActionPerformed
        panelControl.removeAll();
        CtrlInterfaz.habilita(true, empleado, asistencia);
        VtnEmpleados empleados = new VtnEmpleados();
        panelControl.add(empleados).setVisible(true);
    }//GEN-LAST:event_empleadoActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu4MouseClicked
    {//GEN-HEADEREND:event_jMenu4MouseClicked
        VtnLoginAsistencia asistencia = new VtnLoginAsistencia(this, true);
        asistencia.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void asistenciaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_asistenciaMouseClicked
    {//GEN-HEADEREND:event_asistenciaMouseClicked
        panelControl.removeAll();
        VtnAsistencias asistencia = new VtnAsistencias();
        panelControl.add(asistencia).setVisible(true);
    }//GEN-LAST:event_asistenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu administrador;
    private javax.swing.JMenu asistencia;
    private javax.swing.JMenu empleado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu login;
    private javax.swing.JDesktopPane panelControl;
    // End of variables declaration//GEN-END:variables
}
